from enum import Enum


class ManifestStatus(str, Enum):
    DISCOVERED = "DISCOVERED"
    PENDING = "PENDING"
    QUEUED = "QUEUED"
    IN_PROGRESS = "IN_PROGRESS"
    INDEXED = "INDEXED"
    FAILED_RETRYABLE = "FAILED_RETRYABLE"
    FAILED_PERMANENT = "FAILED_PERMANENT"
    SKIPPED_DUPLICATE = "SKIPPED_DUPLICATE"
